### ISSUE TITLE
IETF safe email addresses

### ISSUE THREAD

**Issue by enexusde** [echocat/java-kata-1#5]
I was asked to do this kata. The optional-task 3 is invalid for specific circumstances, lets call them cornercases.

Entering a eMail-Address we usually think about eMail addresses like:`tom.riddle@example.com`
Driving eMail-Addresses to insanity also this is a 100% VALID eMail-Address: `abc:;`!
Unfortunately the `;` in the eMail-Address it is threatened as a .csv-field-separator. I would suggest you either name the email-address more like emailbox-address to be specific OR change all the eMail-Addresses from the cvs-files into eMail-Group-Notations using [double-quotas because they are escapable](https://tools.ietf.org/html/rfc4180#section-2).

According to some [people who made some effort in documentation](https://tools.ietf.org/html/rfc2822#section-3.4).

**Comment by enexusde** [comment]
Ah by the way, since those values are example values please use [example-domains as mail-domain](https://tools.ietf.org/html/rfc2606#section-3).

**Comment by blaubaer** [comment]
@enexusde Thank you for your feedback. The point is, that CSV files can also be escaped. ([see the RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180#section-2)) therefore in cases that the email contains one of those characters it needs to be escaped.
